language: node_js

os: linux
dist: xenial

node_js:
    - 14
    - lts/*

notifications:
    email:
        on_success: never

scripts:
  - npm install codecov -g
  - npm i
  - npm test

after_success:
  - codecov
