language: node_js

node_js:
    - 12
    - lts/*

notifications:
    email:
        on_success: never

scripts:
  - npm install codecov -g
  - npm i
  - npm test
  - npm coverage

after_success:
  - codecov
